Flask site/app/models.py
# Flask modules
from flask_login import UserMixin

_users = []

class User(UserMixin):
    def __init__(self, id, login, password):
        self.id = id
        self.login = login
        self.password = password

    @staticmethod
    def all():
        global _users
        if len(_users) > 0:
            return _users
        with open("users.txt") as f:
            for line in f:
                id, login, password = line.split()
                _users.append(User(id, login, password))
        return _users

    @staticmethod
    def find_by_id(id):
        found = list(filter(lambda x: x.id == id, User.all()))
        return None if len(found) == 0 else found[0]

    @staticmethod
    def find_by_creds(login, password):
        found = list(filter(lambda x: x.login == login and x.password == password, User.all()))
        return None if len(found) == 0 else found[0]

Flask site/app/forms.py
# Flask modules
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    login = StringField('Login', validators=[DataRequired()], render_kw={'placeholder': 'Login'})
    password = PasswordField('Password', validators=[DataRequired()], render_kw={'placeholder': '********'})
    remember_me = BooleanField('Remember me', default=False)
    submit = SubmitField('Log In')

Flask site/app/__init__.py
# Flask modules
from flask import Flask


def create_app(debug: bool = False) -> Flask:
    # Initialize app
    app = Flask(__name__, template_folder='../templates')

    # Setup app configs
    app.config['DEBUG'] = debug
    app.config['SECRET_KEY'] = 'my secret'

    # Initialize extensions
    from app.extensions import bcrypt, csrf, login_manager
    csrf.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)

    # Register blueprints
    from app.routes import routes
    app.register_blueprint(routes)

    return app

Flask site/app/routes.py
from datetime import timedelta

# Flask modules
import flask
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import login_user, logout_user, current_user, login_required

# Local modules
from app.extensions import login_manager
from app.forms import LoginForm
from app.models import User

routes = Blueprint('routes', __name__, url_prefix="/")


@login_manager.user_loader
def load_user(user_id):
    return User.find_by_id(user_id)


@routes.route("/")
@login_required
def home():
    return render_template('index.html')


@routes.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("routes.home"))

    form = LoginForm()

    login = form.login.data
    password = form.password.data
    remember_me = form.remember_me.data

    if flask.request.method == "POST":
        user =  User.find_by_creds(login, password)
        if user is not None:
            flash(f'You successfully sing up!', 'success')
            login_user(user, duration=timedelta.max if remember_me else timedelta(days=1))
            return redirect(flask.request.args.get("next") or url_for("routes.home"))
        else:
            flash(f'Login failed, incorrect login or password','danger')

    return render_template('auth/login.html', form=form)

@routes.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for("routes.login"))

Flask site/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
{% with messages = get_flashed_messages(with_categories=true, category_filter=["success", "info"]) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{ category }}" style="width: 100%; z-index: 999">
    {{ message }}
      <a class="close" href="#" onclick="this.parentElement.remove(); return false">×</a>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<main class="p-2">
    {% block content %}
    {% endblock content %}
</main>

<!-- Include Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

Flask site/templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<h1>Home Page</h1>
<p>Hello there, you are logged in as <span class="text-success font-weight-bold">{{ current_user.login }}</span>.</p>
<a href="{{ url_for('routes.logout') }}">Logout</a>
{% endblock content %}